// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:c0210014-5d20-4124-8554-05a517b363e9",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_f42fqtI7U",
    "aws_user_pools_web_client_id": "ib16k7s5k4m4u78b9oihuoa6l",
    "aws_content_delivery_bucket": "my-app-20190508154800-hostingbucket-master",
    "aws_content_delivery_bucket_region": "eu-west-1",
    "aws_content_delivery_url": "http://my-app-20190508154800-hostingbucket-master.s3-website-eu-west-1.amazonaws.com"
};


export default awsmobile;
